//! Build-time code generator for the `quorums` gorums runtime.
//!
//! Add to your `build.rs`:
//!
//! ```rust,no_run
//! quorums_build::configure()
//!     .method("/mypackage.MyService/ReadQC", quorums_build::CallType::QuorumCall)
//!     .method("/mypackage.MyService/Write",  quorums_build::CallType::Multicast)
//!     .compile(&["proto/my_service.proto"], &["proto"])
//!     .unwrap();
//! ```
//!
//! This compiles the proto file (message types via prost) and generates:
//! - A `{service_name}_client` module with one typed async function per method.
//! - A `{service_name}_server` module with a trait and a `register_*` helper.
//!
//! Include the generated file in your crate with:
//! ```rust,ignore
//! mod pb {
//!     tonic::include_proto!("mypackage");
//! }
//! ```

use std::collections::HashMap;

mod codegen;

// ── Public API ────────────────────────────────────────────────────────────────

/// The gorums call type to use for a proto method.
#[derive(Clone, Debug)]
pub enum CallType {
    /// Single-node two-way call (`rpc_call`).
    RpcCall,
    /// Single-node one-way call (`unicast`).
    Unicast,
    /// Fan-out one-way to all nodes (`multicast`).
    Multicast,
    /// Fan-out two-way, aggregate responses (`quorum_call`).
    QuorumCall,
    /// Fan-out two-way with position-tagged responses (`ordered_quorum_call`).
    OrderedQuorumCall,
    /// Fan-out streaming two-way (`correctable_call`).
    Correctable,
}

/// Builder returned by [`configure`].
pub struct Builder {
    pub(crate) methods: HashMap<String, CallType>,
}

/// Start a new build configuration.
pub fn configure() -> Builder {
    Builder {
        methods: HashMap::new(),
    }
}

impl Builder {
    /// Annotate a proto method with its gorums call type.
    ///
    /// `path` is the full gRPC method path, e.g. `"/storage.Storage/ReadQC"`.
    pub fn method(mut self, path: impl Into<String>, call_type: CallType) -> Self {
        self.methods.insert(path.into(), call_type);
        self
    }

    /// Compile the given proto files and write generated code to `OUT_DIR`.
    ///
    /// Message types are generated by prost.  Gorums wrappers are appended to
    /// the same output file for each proto package.
    pub fn compile(
        self,
        protos: &[&str],
        includes: &[&str],
    ) -> Result<(), Box<dyn std::error::Error>> {
        let generator = codegen::GorumsGenerator {
            methods: self.methods,
        };
        let mut config = prost_build::Config::new();
        config.service_generator(Box::new(generator));
        config.compile_protos(protos, includes)?;
        Ok(())
    }
}
